
package com.poc.pts.domain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ParcelTrackingServiceEndpoint_V1_0", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParcelTrackingServiceEndpointV10 {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws TrackingAppException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createParcelDetails", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.CreateParcelDetails")
    @ResponseWrapper(localName = "createParcelDetailsResponse", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.CreateParcelDetailsResponse")
    public String createParcelDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        ParcelDetails arg0)
        throws TrackingAppException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.pb.pts.domain.ParcelTrackingData
     * @throws TrackingAppException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParcelTrackingDetails", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.GetParcelTrackingDetails")
    @ResponseWrapper(localName = "getParcelTrackingDetailsResponse", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.GetParcelTrackingDetailsResponse")
    public ParcelTrackingData getParcelTrackingDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        ParcelTrackingRequestData arg0)
        throws TrackingAppException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws TrackingAppException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitEvent", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.SubmitEvent")
    @ResponseWrapper(localName = "submitEventResponse", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.SubmitEventResponse")
    public boolean submitEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        EventData arg0)
        throws TrackingAppException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws TrackingAppException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateParcelDetails", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.UpdateParcelDetails")
    @ResponseWrapper(localName = "updateParcelDetailsResponse", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", className = "com.pb.pts.domain.UpdateParcelDetailsResponse")
    public boolean updateParcelDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        ParcelUpdateDetails arg0)
        throws TrackingAppException_Exception
    ;

}
