
package com.poc.pts.domain;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "trackingservice_v1_0", targetNamespace = "http://v1_0.endpoint.service.pts.pb.com/", wsdlLocation = "http://152.144.219.6/pts/tracking_v1_0?wsdl")
public class TrackingserviceV10
    extends Service
{

    private final static URL TRACKINGSERVICEV10_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.poc.pts.domain.TrackingserviceV10 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.poc.pts.domain.TrackingserviceV10 .class.getResource(".");
            url = new URL(baseUrl, "http://152.144.219.6/pts/tracking_v1_0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://152.144.219.6/pts/tracking_v1_0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRACKINGSERVICEV10_WSDL_LOCATION = url;
    }

    public TrackingserviceV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackingserviceV10() {
        super(TRACKINGSERVICEV10_WSDL_LOCATION, new QName("http://v1_0.endpoint.service.pts.pb.com/", "trackingservice_v1_0"));
    }

    /**
     * 
     * @return
     *     returns ParcelTrackingServiceEndpointV10
     */
    @WebEndpoint(name = "ParcelTrackingServiceEndpoint_V1_0Port")
    public ParcelTrackingServiceEndpointV10 getParcelTrackingServiceEndpointV10Port() {
        return super.getPort(new QName("http://v1_0.endpoint.service.pts.pb.com/", "ParcelTrackingServiceEndpoint_V1_0Port"), ParcelTrackingServiceEndpointV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParcelTrackingServiceEndpointV10
     */
    @WebEndpoint(name = "ParcelTrackingServiceEndpoint_V1_0Port")
    public ParcelTrackingServiceEndpointV10 getParcelTrackingServiceEndpointV10Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1_0.endpoint.service.pts.pb.com/", "ParcelTrackingServiceEndpoint_V1_0Port"), ParcelTrackingServiceEndpointV10.class, features);
    }

}
